export interface Phrase {
  english: string;
  chinese: string;
  korean: string;
  japanese: string;
  tagalog: string;
  visaya: string;
  arabic: string;
}

export interface PhraseCategory {
  category: string;
  phrases: Phrase[];
}

export const phrasesData: PhraseCategory[] = [
  {
    category: 'Greetings',
    phrases: [
      {
        english: 'Hello',
        chinese: '你好 (Nǐ hǎo)',
        korean: '안녕하세요 (Annyeonghaseyo)',
        japanese: 'こんにちは (Konnichiwa)',
        tagalog: 'Kamusta',
        visaya: 'Kumusta',
        arabic: 'مرحبا (Marhaba)',
      },
      {
        english: 'Good morning',
        chinese: '早上好 (Zǎoshang hǎo)',
        korean: '좋은 아침이에요 (Joeun achimieyo)',
        japanese: 'おはようございます (Ohayō gozaimasu)',
        tagalog: 'Magandang umaga',
        visaya: 'Maayong buntag',
        arabic: 'صباح الخير (Sabah al-khayr)',
      },
      {
        english: 'Good evening',
        chinese: '晚上好 (Wǎnshàng hǎo)',
        korean: '좋은 저녁이에요 (Joeun jeonyeogieyo)',
        japanese: 'こんばんは (Konbanwa)',
        tagalog: 'Magandang gabi',
        visaya: 'Maayong gabii',
        arabic: "مساء الخير (Masa' al-khayr)",
      },
      {
        english: 'Goodbye',
        chinese: '再见 (Zàijiàn)',
        korean: '안녕히 가세요 (Annyeonghi gaseyo)',
        japanese: 'さようなら (Sayōnara)',
        tagalog: 'Paalam',
        visaya: 'Babay',
        arabic: "مع السلامة (Ma'a as-salama)",
      },
      {
        english: 'Thank you',
        chinese: '谢谢 (Xièxiè)',
        korean: '감사합니다 (Gamsahamnida)',
        japanese: 'ありがとうございます (Arigatō gozaimasu)',
        tagalog: 'Salamat',
        visaya: 'Salamat',
        arabic: 'شكراً (Shukran)',
      },
      {
        english: "You're welcome",
        chinese: '不客气 (Bù kèqì)',
        korean: '천만에요 (Cheonmaneyo)',
        japanese: 'どういたしまして (Dōitashimashite)',
        tagalog: 'Walang anuman',
        visaya: "Wala'y sapayan",
        arabic: 'عفواً (Afwan)',
      },
    ],
  },
  {
    category: 'Basic Phrases',
    phrases: [
      {
        english: 'Yes',
        chinese: '是 (Shì)',
        korean: '네 (Ne)',
        japanese: 'はい (Hai)',
        tagalog: 'Oo',
        visaya: 'Oo',
        arabic: "نعم (Na'am)",
      },
      {
        english: 'No',
        chinese: '不 (Bù)',
        korean: '아니요 (Aniyo)',
        japanese: 'いいえ (Iie)',
        tagalog: 'Hindi',
        visaya: 'Dili',
        arabic: 'لا (La)',
      },
      {
        english: 'Please',
        chinese: '请 (Qǐng)',
        korean: '주세요 (Juseyo)',
        japanese: 'お願いします (Onegaishimasu)',
        tagalog: 'Pakiusap',
        visaya: 'Palihug',
        arabic: 'من فضلك (Min fadlak)',
      },
      {
        english: 'Excuse me',
        chinese: '对不起 (Duìbùqǐ)',
        korean: '실례합니다 (Sillyehamnida)',
        japanese: 'すみません (Sumimasen)',
        tagalog: 'Excuse me po',
        visaya: 'Pasensya',
        arabic: 'عفواً (Afwan)',
      },
      {
        english: "I'm sorry",
        chinese: '抱歉 (Bàoqiàn)',
        korean: '죄송합니다 (Joesonghamnida)',
        japanese: 'ごめんなさい (Gomennasai)',
        tagalog: 'Pasensya na',
        visaya: 'Pasayloa ko',
        arabic: 'آسف (Aasif)',
      },
      {
        english: 'Do you speak English?',
        chinese: '你会说英语吗？ (Nǐ huì shuō yīngyǔ ma?)',
        korean: '영어 하실 수 있나요? (Yeongeo hasil su innayo?)',
        japanese: '英語を話せますか？ (Eigo o hanasemasu ka?)',
        tagalog: 'Nagsasalita ka ba ng Ingles?',
        visaya: 'Kabalo ka mag ininglis?',
        arabic: 'هل تتكلم الإنجليزية؟ (Hal tatakallam al-ingliziyya?)',
      },
      {
        english: "I don't understand",
        chinese: '我不明白 (Wǒ bù míngbái)',
        korean: '이해가 안 돼요 (Ihaega an dwaeyo)',
        japanese: '分かりません (Wakarimasen)',
        tagalog: 'Hindi ko maintindihan',
        visaya: 'Wala ko kasabot',
        arabic: 'لا أفهم (La afham)',
      },
      {
        english: 'Help!',
        chinese: '救命！ (Jiùmìng!)',
        korean: '도와주세요! (Dowajuseyo!)',
        japanese: '助けて！ (Tasukete!)',
        tagalog: 'Tulong!',
        visaya: 'Tabang!',
        arabic: "مساعدة! (Musa'ada!)",
      },
    ],
  },
  {
    category: 'At the Restaurant',
    phrases: [
      {
        english: 'Menu please',
        chinese: '请给我菜单 (Qǐng gěi wǒ càidān)',
        korean: '메뉴 주세요 (Menyu juseyo)',
        japanese: 'メニューをお願いします (Menyū o onegaishimasu)',
        tagalog: 'Menu po',
        visaya: 'Menu palihug',
        arabic: "القائمة من فضلك (Al-qa'ima min fadlak)",
      },
      {
        english: 'Water please',
        chinese: '请给我水 (Qǐng gěi wǒ shuǐ)',
        korean: '물 주세요 (Mul juseyo)',
        japanese: 'お水をください (Omizu o kudasai)',
        tagalog: 'Tubig po',
        visaya: 'Tubig palihug',
        arabic: "ماء من فضلك (Ma' min fadlak)",
      },
      {
        english: 'The bill please',
        chinese: '请结账 (Qǐng jiézhàng)',
        korean: '계산서 주세요 (Gyesanseo juseyo)',
        japanese: 'お会計をお願いします (Okaikei o onegaishimasu)',
        tagalog: 'Bayad na po',
        visaya: 'Bayad na palihug',
        arabic: 'الفاتورة من فضلك (Al-fatura min fadlak)',
      },
      {
        english: 'This is delicious',
        chinese: '这很好吃 (Zhè hěn hǎochī)',
        korean: '정말 맛있어요 (Jeongmal masisseoyo)',
        japanese: 'これは美味しいです (Kore wa oishii desu)',
        tagalog: 'Masarap ito',
        visaya: 'Lami ni',
        arabic: 'هذا لذيذ (Hatha ladhidh)',
      },
      {
        english: "I'm vegetarian",
        chinese: '我是素食者 (Wǒ shì sùshí zhě)',
        korean: '저는 채식주의자예요 (Jeoneun chaesikjuuijayeyo)',
        japanese: '私はベジタリアンです (Watashi wa bejitarian desu)',
        tagalog: 'Vegetarian ako',
        visaya: 'Vegetarian ko',
        arabic: 'أنا نباتي (Ana nabati)',
      },
      {
        english: 'No spicy please',
        chinese: '请不要辣 (Qǐng bùyào là)',
        korean: '맵지 않게 주세요 (Maepji anke juseyo)',
        japanese:
          '辛くないものでお願いします (Karakunai mono de onegaishimasu)',
        tagalog: 'Hindi maanghang',
        visaya: 'Dili halang',
        arabic: 'بدون حار من فضلك (Bidun har min fadlak)',
      },
      {
        english: 'Breakfast',
        chinese: '早餐 (Zǎocān)',
        korean: '아침 식사 (Achim siksa)',
        japanese: '朝食 (Chōshoku)',
        tagalog: 'Almusal',
        visaya: 'Pamahaw',
        arabic: 'فطور (Futur)',
      },
      {
        english: 'Lunch',
        chinese: '午餐 (Wǔcān)',
        korean: '점심 식사 (Jeomsim siksa)',
        japanese: '昼食 (Chūshoku)',
        tagalog: 'Tanghalian',
        visaya: 'Paniudto',
        arabic: "غداء (Ghada')",
      },
      {
        english: 'Dinner',
        chinese: '晚餐 (Wǎncān)',
        korean: '저녁 식사 (Jeonyeok siksa)',
        japanese: '夕食 (Yūshoku)',
        tagalog: 'Hapunan',
        visaya: 'Panihapon',
        arabic: "عشاء (Asha')",
      },
    ],
  },
  {
    category: 'Shopping',
    phrases: [
      {
        english: 'How much is this?',
        chinese: '这个多少钱？ (Zhège duōshǎo qián?)',
        korean: '이거 얼마예요? (Igeo eolmayeyo?)',
        japanese: 'これはいくらですか？ (Kore wa ikura desu ka?)',
        tagalog: 'Magkano ito?',
        visaya: 'Pila ni?',
        arabic: 'بكم هذا؟ (Bikam hatha?)',
      },
      {
        english: 'Too expensive',
        chinese: '太贵了 (Tài guì le)',
        korean: '너무 비싸요 (Neomu bissayo)',
        japanese: '高すぎます (Takasugimasu)',
        tagalog: 'Mahal masyado',
        visaya: 'Mahal kaayo',
        arabic: 'غالي جداً (Ghali jiddan)',
      },
      {
        english: 'Can I get a discount?',
        chinese: '可以打折吗？ (Kěyǐ dǎzhé ma?)',
        korean: '할인 받을 수 있나요? (Harin badeul su innayo?)',
        japanese: '割引できますか？ (Waribiki dekimasu ka?)',
        tagalog: 'May discount ba?',
        visaya: 'May discount ba?',
        arabic: 'هل يمكنني الحصول على خصم؟ (Hal yumkinuni al-husul ala khasm?)',
      },
      {
        english: "I'll take it",
        chinese: '我要这个 (Wǒ yào zhège)',
        korean: '이거 살게요 (Igeo salgeyo)',
        japanese: 'これを買います (Kore o kaimasu)',
        tagalog: 'Kukunin ko',
        visaya: 'Kuhaon nako',
        arabic: "سآخذه (Sa'akhudhuh)",
      },
      {
        english: 'Do you accept credit cards?',
        chinese: '你们接受信用卡吗？ (Nǐmen jiēshòu xìnyòngkǎ ma?)',
        korean: '신용카드 되나요? (Sinyongkadeu doenayo?)',
        japanese:
          'クレジットカードは使えますか？ (Kurejittokādo wa tsukaemasu ka?)',
        tagalog: 'Tumatanggap ba kayo ng credit card?',
        visaya: 'Modawat ba mo ug credit card?',
        arabic: "هل تقبلون بطاقات الائتمان؟ (Hal taqbalun bitaqat al-i'timan?)",
      },
      {
        english: 'Just looking',
        chinese: '只是看看 (Zhǐshì kàn kàn)',
        korean: '그냥 구경하는 거예요 (Geunyang gugyeonghaneun geoyeyo)',
        japanese: '見ているだけです (Mite iru dake desu)',
        tagalog: 'Tingnan lang',
        visaya: 'Tan-aw ra',
        arabic: 'أتفرج فقط (Atafarraj faqat)',
      },
    ],
  },
  {
    category: 'Transportation',
    phrases: [
      {
        english: 'Where is the bus stop?',
        chinese: '公交车站在哪里？ (Gōngjiāo chēzhàn zài nǎlǐ?)',
        korean: '버스 정류장이 어디예요? (Beoseu jeongnyujangi eodiyeyo?)',
        japanese: 'バス停はどこですか？ (Basutei wa doko desu ka?)',
        tagalog: 'Nasaan ang bus stop?',
        visaya: 'Asa ang bus stop?',
        arabic: 'أين موقف الحافلة؟ (Ayna mawqif al-hafila?)',
      },
      {
        english: 'Take me to the airport',
        chinese: '带我去机场 (Dài wǒ qù jīchǎng)',
        korean: '공항으로 가주세요 (Gonghang-euro gajuseyo)',
        japanese: '空港まで行ってください (Kūkō made itte kudasai)',
        tagalog: 'Dalhin mo ako sa airport',
        visaya: 'Dad-a ko sa airport',
        arabic: 'خذني إلى المطار (Khudhni ila al-matar)',
      },
      {
        english: 'How much is the fare?',
        chinese: '车费多少？ (Chēfèi duōshǎo?)',
        korean: '요금이 얼마예요? (Yogeumi eolmayeyo?)',
        japanese: '運賃はいくらですか？ (Unchin wa ikura desu ka?)',
        tagalog: 'Magkano ang pamasahe?',
        visaya: 'Pila ang plite?',
        arabic: 'كم الأجرة؟ (Kam al-ujra?)',
      },
      {
        english: 'Stop here please',
        chinese: '请在这里停 (Qǐng zài zhèlǐ tíng)',
        korean: '여기서 세워주세요 (Yeogiseo sewojuseyo)',
        japanese: 'ここで止めてください (Koko de tomete kudasai)',
        tagalog: 'Para dito',
        visaya: 'Para diri',
        arabic: 'توقف هنا من فضلك (Tawaqqaf huna min fadlak)',
      },
      {
        english: 'I need a taxi',
        chinese: '我需要出租车 (Wǒ xūyào chūzū chē)',
        korean: '택시가 필요해요 (Taeksiga piryohaeyo)',
        japanese: 'タクシーが必要です (Takushī ga hitsuyō desu)',
        tagalog: 'Kailangan ko ng taxi',
        visaya: 'Kinahanglan kog taxi',
        arabic: 'أحتاج تاكسي (Ahtaj taxi)',
      },
      {
        english: 'Train station',
        chinese: '火车站 (Huǒchē zhàn)',
        korean: '기차역 (Gichayeok)',
        japanese: '駅 (Eki)',
        tagalog: 'Istasyon ng tren',
        visaya: 'Estasyon sa tren',
        arabic: 'محطة القطار (Mahattat al-qitar)',
      },
    ],
  },
  {
    category: 'Hotel/Accommodation',
    phrases: [
      {
        english: 'I have a reservation',
        chinese: '我有预订 (Wǒ yǒu yùdìng)',
        korean: '예약했어요 (Yeyakaesseoyo)',
        japanese: '予約しています (Yoyaku shite imasu)',
        tagalog: 'May reservation ako',
        visaya: 'Naa koy reservation',
        arabic: 'لدي حجز (Ladayya hajz)',
      },
      {
        english: 'Can I see the room?',
        chinese: '我可以看看房间吗？ (Wǒ kěyǐ kànkan fángjiān ma?)',
        korean: '방을 볼 수 있나요? (Bang-eul bol su innayo?)',
        japanese:
          '部屋を見せていただけますか？ (Heya o misete itadakemasu ka?)',
        tagalog: 'Pwede ko bang makita ang kwarto?',
        visaya: 'Pwede ko motan-aw sa kwarto?',
        arabic: "هل يمكنني رؤية الغرفة؟ (Hal yumkinuni ru'yat al-ghurfa?)",
      },
      {
        english: 'What time is check-out?',
        chinese: '退房时间是几点？ (Tuì fáng shíjiān shì jǐ diǎn?)',
        korean: '체크아웃 시간이 몇 시예요? (Chekeuaut sigani myeot siyeyo?)',
        japanese: 'チェックアウトは何時ですか？ (Chekkuauto wa nanji desu ka?)',
        tagalog: 'Anong oras ang check-out?',
        visaya: 'Unsang orasa ang check-out?',
        arabic: "متى موعد المغادرة؟ (Mata maw'id al-mughadara?)",
      },
      {
        english: "The air conditioning doesn't work",
        chinese: '空调不工作 (Kōngtiáo bù gōngzuò)',
        korean: '에어컨이 안 돼요 (Eeokeon-i an dwaeyo)',
        japanese: 'エアコンが動きません (Eakon ga ugokimasen)',
        tagalog: 'Hindi gumagana ang aircon',
        visaya: 'Dili moandar ang aircon',
        arabic: "المكيف لا يعمل (Al-mukayyif la ya'mal)",
      },
      {
        english: 'Can I have extra towels?',
        chinese: '可以给我额外的毛巾吗？ (Kěyǐ gěi wǒ éwài de máojīn ma?)',
        korean: '수건 더 주실 수 있나요? (Sugeon deo jusil su innayo?)',
        japanese:
          'タオルを追加でいただけますか？ (Taoru o tsuika de itadakemasu ka?)',
        tagalog: 'Pwede pa ba ng tuwalya?',
        visaya: 'Pwede pa ba ug tuwalya?',
        arabic:
          'هل يمكنني الحصول على مناشف إضافية؟ (Hal yumkinuni al-husul ala manashif idafiyya?)',
      },
      {
        english: 'Wi-Fi password?',
        chinese: 'Wi-Fi密码？ (Wi-Fi mìmǎ?)',
        korean: '와이파이 비밀번호가 뭐예요? (Waipai bimilbeonhoga mwoyeyo?)',
        japanese:
          'Wi-Fiのパスワードは何ですか？ (Wi-Fi no pasuwādo wa nan desu ka?)',
        tagalog: 'Password ng Wi-Fi?',
        visaya: 'Password sa Wi-Fi?',
        arabic: 'ما كلمة مرور الواي فاي؟ (Ma kalimat murur al-wifi?)',
      },
    ],
  },
  {
    category: 'Directions',
    phrases: [
      {
        english: 'Where is...?',
        chinese: '...在哪里？ (...zài nǎlǐ?)',
        korean: '...이/가 어디예요? (...i/ga eodiyeyo?)',
        japanese: '...はどこですか？ (...wa doko desu ka?)',
        tagalog: 'Nasaan ang...?',
        visaya: 'Asa ang...?',
        arabic: 'أين...؟ (Ayna...?)',
      },
      {
        english: 'Turn left',
        chinese: '向左转 (Xiàng zuǒ zhuǎn)',
        korean: '왼쪽으로 가세요 (Oenjjog-euro gaseyo)',
        japanese: '左に曲がってください (Hidari ni magatte kudasai)',
        tagalog: 'Kumaliwa',
        visaya: 'Liko sa wala',
        arabic: "انعطف يساراً (In'atif yasaran)",
      },
      {
        english: 'Turn right',
        chinese: '向右转 (Xiàng yòu zhuǎn)',
        korean: '오른쪽으로 가세요 (Oreunjjog-euro gaseyo)',
        japanese: '右に曲がってください (Migi ni magatte kudasai)',
        tagalog: 'Kumanan',
        visaya: 'Liko sa tuo',
        arabic: "انعطف يميناً (In'atif yaminan)",
      },
      {
        english: 'Go straight',
        chinese: '直走 (Zhí zǒu)',
        korean: '직진하세요 (Jikjinhaseyo)',
        japanese: 'まっすぐ行ってください (Massugu itte kudasai)',
        tagalog: 'Diretso lang',
        visaya: 'Diretso lang',
        arabic: 'سر مباشرة (Sir mubashara)',
      },
      {
        english: 'How far is it?',
        chinese: '有多远？ (Yǒu duō yuǎn?)',
        korean: '얼마나 멀어요? (Eolmana meoreoyo?)',
        japanese: 'どのくらい遠いですか？ (Donokurai tōi desu ka?)',
        tagalog: 'Gaano kalayo?',
        visaya: 'Unsa kalayo?',
        arabic: 'كم المسافة؟ (Kam al-masafa?)',
      },
      {
        english: 'Near',
        chinese: '近 (Jìn)',
        korean: '가까워요 (Gakkaoyo)',
        japanese: '近い (Chikai)',
        tagalog: 'Malapit',
        visaya: 'Duol',
        arabic: 'قريب (Qarib)',
      },
      {
        english: 'Far',
        chinese: '远 (Yuǎn)',
        korean: '멀어요 (Meoreoyo)',
        japanese: '遠い (Tōi)',
        tagalog: 'Malayo',
        visaya: 'Layo',
        arabic: "بعيد (Ba'id)",
      },
    ],
  },
  {
    category: 'Emergency',
    phrases: [
      {
        english: 'Call the police!',
        chinese: '叫警察！ (Jiào jǐngchá!)',
        korean: '경찰을 불러주세요! (Gyeongchareul bulleojuseyo!)',
        japanese: '警察を呼んでください！ (Keisatsu o yonde kudasai!)',
        tagalog: 'Tawagan ang pulis!',
        visaya: 'Tawagi ang pulis!',
        arabic: 'اتصل بالشرطة! (Ittasil bish-shurta!)',
      },
      {
        english: 'I need a doctor',
        chinese: '我需要医生 (Wǒ xūyào yīshēng)',
        korean: '의사가 필요해요 (Uisaga piryohaeyo)',
        japanese: '医者が必要です (Isha ga hitsuyō desu)',
        tagalog: 'Kailangan ko ng doktor',
        visaya: 'Kinahanglan kog doktor',
        arabic: 'أحتاج طبيب (Ahtaj tabib)',
      },
      {
        english: 'Where is the hospital?',
        chinese: '医院在哪里？ (Yīyuàn zài nǎlǐ?)',
        korean: '병원이 어디예요? (Byeongwon-i eodiyeyo?)',
        japanese: '病院はどこですか？ (Byōin wa doko desu ka?)',
        tagalog: 'Nasaan ang ospital?',
        visaya: 'Asa ang hospital?',
        arabic: 'أين المستشفى؟ (Ayna al-mustashfa?)',
      },
      {
        english: 'I lost my passport',
        chinese: '我丢了护照 (Wǒ diū le hùzhào)',
        korean: '여권을 잃어버렸어요 (Yeogwoneul ireobeoryeosseoyo)',
        japanese: 'パスポートを失くしました (Pasupōto o nakushimashita)',
        tagalog: 'Nawala ang passport ko',
        visaya: 'Nawala ang akong passport',
        arabic: 'فقدت جواز سفري (Faqadtu jawaz safari)',
      },
      {
        english: 'Fire!',
        chinese: '着火了！ (Zháohuǒ le!)',
        korean: '불이야! (Buriya!)',
        japanese: '火事です！ (Kaji desu!)',
        tagalog: 'Sunog!',
        visaya: 'Sunog!',
        arabic: 'حريق! (Hariq!)',
      },
      {
        english: 'Ambulance',
        chinese: '救护车 (Jiùhùchē)',
        korean: '구급차 (Gugeupcha)',
        japanese: '救急車 (Kyūkyūsha)',
        tagalog: 'Ambulansya',
        visaya: 'Ambulansya',
        arabic: "إسعاف (Is'af)",
      },
    ],
  },
  {
    category: 'Numbers & Money',
    phrases: [
      {
        english: 'One',
        chinese: '一 (Yī)',
        korean: '하나 (Hana)',
        japanese: '一 (Ichi)',
        tagalog: 'Isa',
        visaya: 'Usa',
        arabic: 'واحد (Wahid)',
      },
      {
        english: 'Two',
        chinese: '二 (Èr)',
        korean: '둘 (Dul)',
        japanese: '二 (Ni)',
        tagalog: 'Dalawa',
        visaya: 'Duha',
        arabic: 'اثنان (Ithnan)',
      },
      {
        english: 'Three',
        chinese: '三 (Sān)',
        korean: '셋 (Set)',
        japanese: '三 (San)',
        tagalog: 'Tatlo',
        visaya: 'Tulo',
        arabic: 'ثلاثة (Thalatha)',
      },
      {
        english: 'Four',
        chinese: '四 (Sì)',
        korean: '넷 (Net)',
        japanese: '四 (Shi/Yon)',
        tagalog: 'Apat',
        visaya: 'Upat',
        arabic: "أربعة (Arba'a)",
      },
      {
        english: 'Five',
        chinese: '五 (Wǔ)',
        korean: '다섯 (Daseot)',
        japanese: '五 (Go)',
        tagalog: 'Lima',
        visaya: 'Lima',
        arabic: 'خمسة (Khamsa)',
      },
      {
        english: 'Ten',
        chinese: '十 (Shí)',
        korean: '열 (Yeol)',
        japanese: '十 (Jū)',
        tagalog: 'Sampu',
        visaya: 'Napulo',
        arabic: 'عشرة (Ashara)',
      },
      {
        english: 'One hundred',
        chinese: '一百 (Yībǎi)',
        korean: '백 (Baek)',
        japanese: '百 (Hyaku)',
        tagalog: 'Isang daan',
        visaya: 'Usa ka gatos',
        arabic: "مائة (Mi'a)",
      },
      {
        english: 'One thousand',
        chinese: '一千 (Yīqiān)',
        korean: '천 (Cheon)',
        japanese: '千 (Sen)',
        tagalog: 'Isang libo',
        visaya: 'Usa ka libo',
        arabic: 'ألف (Alf)',
      },
    ],
  },
];
